# Generated by Django 4.2.6 on 2023-11-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="media")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="media")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "countries",
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.IntegerField()),
                ("description", models.TextField()),
                ("featured", models.BooleanField(default=False)),
                ("image", models.ImageField(blank=True, upload_to="media")),
                ("name", models.CharField(max_length=255)),
                ("participants", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("score", models.FloatField(blank=True)),
                ("valuations", models.IntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="offers.category"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="offers.country"
                    ),
                ),
            ],
        ),
    ]
