# Generated by Django 4.2.6 on 2023-11-28 14:17

from django.db import migrations


def loaddata(apps, schema_editor):
    Category = apps.get_model('offers', 'Category')
    category = Category.objects.create(image="https://www.karebaviatges.com/es/blog/wp-content/uploads/aventura-verano.jpg",
                                       name="Adventure",
                                       description="For the thrill-seekers and adrenaline junkies, our adventure travel package offers an exhilarating escapade. From zip-lining through Costa Rican rainforests to scaling the rugged peaks of the Himalayas, each destination promises heart-pounding experiences. Dive into the unknown with activities like snorkeling in the Great Barrier Reef or trekking through the Amazon rainforest, creating memories that will last a lifetime.")
    category.save()

    Country = apps.get_model('offers', 'Country')
    country = Country.objects.create(image="https://www.westernunion.com/blog/wp-content/uploads/2023/02/6-lugares-turisticos-para-visitar-en-Francia.jpg",
                                     name="France",
                                     description="Welcome to the enchanting world of France, where romance, culture, and breathtaking landscapes converge to create an unparalleled travel experience. Nestled in the heart of Western Europe, France is a tapestry of historic charm and modern allure.")
    country.save()

    Offer = apps.get_model('offers', 'Offer')
    offer = Offer.objects.create(country=country,
                                 days=5,
                                 description="Embark on an exhilarating adventure through the diverse landscapes of France!",
                                 featured=False,
                                 image="https://www.westernunion.com/blog/wp-content/uploads/2023/02/6-lugares-turisticos-para-visitar-en-Francia.jpg",
                                 name="Wild adventure in France!",
                                 price=350.95)
    offer.categories.add(category)
    offer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(loaddata),
    ]
