# Generated by Django 4.2.5 on 2023-11-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
